start handling common signals + prefix logs with [logbt]

diff --git a/bin/logbt b/bin/logbt
--- a/bin/logbt
+++ b/bin/logbt
@@ -41,81 +41,70 @@ function process_core() {
 }
 
 function find_core_by_pid() {
-  local code=${1}
-  local program=${2}
-  local core_directory=${3}
-  local debugger=${4}
+  local program=${1}
+  local core_directory=${2}
+  local debugger=${3}
+  local child_pid=${4}
   if [[ ${PLATFORM_UNAME} == "Darwin" ]]; then
-    local single_corefile="${core_directory}/${REQUIRED_FILENAME}.${CHILD_PID}"
+    local single_corefile="${core_directory}/${REQUIRED_FILENAME}.${child_pid}"
     if [ -e ${single_corefile} ]; then
-      echo "Found corefile at ${single_corefile}"
+      echo "[logbt] Found corefile at ${single_corefile}"
       process_core ${program} ${single_corefile} ${debugger}
     else
-      if [[ ${code} != 0 ]]; then
-          echo "No corefile found at ${single_corefile}"
-      fi
+      echo "[logbt] No corefile found at ${single_corefile}"
     fi
   else
-    local SEARCH_PATTERN_BY_PID="${REQUIRED_FILENAME}.${CHILD_PID}.*"
+    local SEARCH_PATTERN_BY_PID="${REQUIRED_FILENAME}.${child_pid}.*"
     local hit=false
     for corefile in ${core_directory}/${SEARCH_PATTERN_BY_PID}; do
-      echo "Found corefile at ${corefile}"
+      echo "[logbt] Found corefile at ${corefile}"
       # extract program name from corefile
       filename=$(basename "${corefile}")
       binary_program=/$(echo ${filename##*.\!} | tr "!" "/")
       process_core ${binary_program} ${corefile} ${debugger}
       hit=true
     done
-    if [[ ${hit} == false ]] && [[ ${code} != 0 ]]; then
-        echo "No corefile found at ${core_directory}/${SEARCH_PATTERN_BY_PID}"
+    if [[ ${hit} == false ]]; then
+        echo "[logbt] No corefile found at ${core_directory}/${SEARCH_PATTERN_BY_PID}"
     fi
   fi  
 }
 
 function find_remaining_cores() {
-  local code=${1}
-  local program=${2}
-  local core_directory=${3}
-  local debugger=${4}
-  local SEARCH_PATTERN_NON_TRACKED="${REQUIRED_FILENAME}.*"
-  local hit=false
-  for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
-    echo "Found corefile (non-tracked) at ${corefile}"
-    hit=true
-  done
-  if [[ ${code} != 0 ]]; then
-    if [[ ${hit} == true ]]; then
-      echo "Processing cores..."
-    fi
-    for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
-      # below two lines are linux specific, but harmless to run on osx
-      filename=$(basename "${corefile}")
-      binary_program=/$(echo ${filename##*.\!} | tr "!" "/")
-      process_core ${binary_program} ${corefile} ${debugger}
-    done
-  else
-    if [[ ${hit} == true ]]; then
-      echo "Skipping processing cores..."
-    fi
-  fi  
-}
-
-function backtrace {
-  local code=$?
   local program=${1}
   local core_directory=${2}
   local debugger=${3}
-  echo "${program} exited with code:${code}"
-  find_core_by_pid ${code} ${program} ${core_directory} ${debugger}
-  find_remaining_cores ${code} ${program} ${core_directory} ${debugger}
-  exit $code
+  local SEARCH_PATTERN_NON_TRACKED="${REQUIRED_FILENAME}.*"
+  local hit=false
+  for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
+    echo "[logbt] Found corefile (non-tracked) at ${corefile}"
+    hit=true
+  done
+  if [[ ${hit} == true ]]; then
+    echo "[logbt] Processing cores..."
+  fi
+  for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
+    # below two lines are linux specific, but harmless to run on osx
+    filename=$(basename "${corefile}")
+    binary_program=/$(echo ${filename##*.\!} | tr "!" "/")
+    process_core ${binary_program} ${corefile} ${debugger}
+  done
+}
+
+function backtrace {
+  local program=${1}
+  local core_directory=${2}
+  local debugger=${3}
+  local child_pid=${4}
+  find_core_by_pid ${program} ${core_directory} ${debugger} ${child_pid}
+  find_remaining_cores ${program} ${core_directory} ${debugger}
 }
 
 function warn_on_existing_cores() {
   local core_directory=${1}
   local SEARCH_PATTERN_NON_TRACKED="${REQUIRED_FILENAME}.*"
   for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
-    echo "WARNING: Found corefile (existing) at ${corefile}"
+    echo "[logbt] WARNING: Found corefile (existing) at ${corefile}"
   done
 }
 
@@ -162,14 +151,39 @@ function validate_core_pattern() {
     error "unexpected core_pattern: ${core_pattern}"
   fi  
 }
+
+function trap_with_arg() {
+  func="$1" ; shift
+  for sig in {TERM,INT,HUP,TRAP,PIPE,STOP,SEGV,USR1}; do
+    trap "$func $@ $sig" $sig
+  done
+}
+
+function signal_handler() {
+  local code=$?
+  local program=${1}
+  local child_pid=${2}
+  local sig=${3}
+  echo "[logbt] received signal:${code} (${sig})"
+  echo "[logbt] sending SIGTERM to ${program} (${child_pid})"
+  kill -TERM ${child_pid}
+  CHILD_EXIT=0
+  wait ${child_pid} || CHILD_EXIT=$?
+  if [[ ${CHILD_EXIT} != 143 ]]; then
+    error "Child process exited abnormally: ${CHILD_EXIT}"
+  fi
+  exit ${code}
+}
+
 function launch_and_wait() {
 
+  local program=${1}
   local core_pattern=$(get_core_pattern)
   validate_core_pattern ${core_pattern}
 
   local core_directory=$(dirname ${core_pattern})
-  echo "Using corefile location: ${core_directory}"
-  echo "Using core_pattern: $(basename ${core_pattern})"
+  echo "[logbt] using corefile location: ${core_directory}"
+  echo "[logbt] using core_pattern: $(basename ${core_pattern})"
 
   # ensure we have a debugger installed
   if ! which ${DEBUGGER} > /dev/null; then
@@ -177,7 +191,7 @@ function launch_and_wait() {
   fi
 
   if [[ ! -d ${core_directory} ]]; then
-    echo "Creating directory for core files at '${core_directory}'"
+    echo "[logbt] creating directory for core files at '${core_directory}'"
     mkdir -p -m a+w ${core_directory}
   fi
 
@@ -185,28 +199,44 @@ function launch_and_wait() {
 
   warn_on_existing_cores ${core_directory}
 
-  # Hook up function to run when logbt exits
-  trap "backtrace $1 ${core_directory} ${DEBUGGER}" EXIT
-
   # Enable corefile generation
   ulimit -c unlimited
 
   # Run the child process in a background process
   # in order to get the PID
-  $* & export CHILD_PID=$!
+  $* & CHILD_PID=$!
 
-  # Keep logbt running as long as the child is running
-  # to be able to hook into a potential crash
-  wait ${CHILD_PID}  
+  # Hook up function to run when logbt received signal
+  trap_with_arg signal_handler "${program} ${CHILD_PID}"
+
+  # Wait for child and attempt to generate a backtrace if child exits in non-zero way
+  wait_for_child ${program} ${core_directory} ${DEBUGGER} ${CHILD_PID}
+}
+
+function wait_for_child() {
+  local program=${1}
+  local core_directory=${2}
+  local debugger=${3}
+  local child_pid=${4}
+  CHILD_RETURN=0
+  wait ${child_pid} || CHILD_RETURN=$?
+  local exit_msg="logbt saw '${program}' exit with code:${CHILD_RETURN}"
+  if [[ ${CHILD_RETURN} != 0 ]]; then
+    exit_msg="${exit_msg} ($(kill -l ${CHILD_RETURN}))"
+    echo ${exit_msg}
+    backtrace ${program} ${core_directory} ${DEBUGGER} ${child_pid}
+  fi
+  # exit logbt with the same code as the child
+  exit ${CHILD_RETURN}
 }
 
 function setup_and_exit() {
   local settable_core_pattern=$(get_target_core_pattern)
   if [[ ${PLATFORM_UNAME} == "Linux" ]]; then
-    echo "Setting $(cat /proc/sys/kernel/core_pattern) -> ${settable_core_pattern}"
+    echo "[logbt] setting $(cat /proc/sys/kernel/core_pattern) -> ${settable_core_pattern}"
     echo "${settable_core_pattern}" > /proc/sys/kernel/core_pattern
   elif [[ ${PLATFORM_UNAME} == "Darwin" ]]; then
-    echo "Setting $(sysctl -n kern.corefile) -> ${settable_core_pattern}"
+    echo "[logbt] setting $(sysctl -n kern.corefile) -> ${settable_core_pattern}"
     sysctl kern.corefile=${settable_core_pattern}
   fi
 
@@ -215,7 +245,7 @@ function setup_and_exit() {
   local core_directory=$(dirname ${core_pattern})
 
   if [[ ! -d ${core_directory} ]]; then
-    echo "Creating directory for core files at '${core_directory}'"
+    echo "[logbt] creating directory for core files at '${core_directory}'"
     mkdir -p -m a+w ${core_directory}
   fi
 
@@ -250,7 +280,7 @@ function test_and_exit() {
     cat /tmp/logbt-stderr
     error "Expected stderr to contain 'core dumped'"
   fi
-  echo "Success"
+  echo "[logbt] success"
   # cleanup
   rm /tmp/logbt-stderr
   rm /tmp/logbt-stdout
