refactor to avoid global variables

diff --git a/bin/logbt b/bin/logbt
--- a/bin/logbt
+++ b/bin/logbt
@@ -4,40 +4,42 @@ set -eu
 set -o pipefail
 shopt -s nullglob
 
-export CORE_DIRECTORY=/tmp/logbt-coredumps
-
 function error() {
   >&2 echo "$@"
   exit 1
 }
 
 function process_core() {
+  local program=${1}
+  local corefile=${2}
   if [[ $(uname -s) == 'Darwin' ]]; then
-    lldb --core ${2} --batch -o 'thread backtrace all' -o 'quit'
+    lldb --core ${corefile} --batch -o 'thread backtrace all' -o 'quit'
   else
-    gdb ${1} --core ${2} -ex "set pagination 0" -ex "thread apply all bt" --batch
+    gdb ${program} --core ${corefile} -ex "set pagination 0" -ex "thread apply all bt" --batch
   fi
   # note: on OS X the -f avoids a hang on prompt 'remove write-protected regular file?'
-  rm -f ${2}
+  rm -f ${corefile}
 }
 
 function backtrace {
   local code=$?
-  echo "$1 exited with code:${code}"
+  local program=${1}
+  local core_directory=${2}
+  echo "${program} exited with code:${code}"
   if [[ $(uname -s) == 'Darwin' ]]; then
-    local COREFILE="${CORE_DIRECTORY}/core.${CHILD_PID}"
-    if [ -e ${COREFILE} ]; then
-      echo "Found corefile at ${COREFILE}"
-      process_core $1 ${COREFILE}
+    local single_corefile="${core_directory}/core.${CHILD_PID}"
+    if [ -e ${single_corefile} ]; then
+      echo "Found corefile at ${single_corefile}"
+      process_core ${program} ${single_corefile}
     else
       if [[ ${code} != 0 ]]; then
-          echo "No corefile found at ${COREFILE}"
+          echo "No corefile found at ${single_corefile}"
       fi
     fi
   else
     local SEARCH_PATTERN_BY_PID="core.${CHILD_PID}.*"
     local hit=false
-    for corefile in ${CORE_DIRECTORY}/${SEARCH_PATTERN_BY_PID}; do
+    for corefile in ${core_directory}/${SEARCH_PATTERN_BY_PID}; do
       echo "Found corefile at ${corefile}"
       # extract program name from corefile
       filename=$(basename "${corefile}")
@@ -46,12 +48,12 @@ function backtrace {
       hit=true
     done
     if [[ ${hit} == false ]] && [[ ${code} != 0 ]]; then
-        echo "No corefile found at ${CORE_DIRECTORY}/${SEARCH_PATTERN_BY_PID}"
+        echo "No corefile found at ${core_directory}/${SEARCH_PATTERN_BY_PID}"
     fi
   fi
   local SEARCH_PATTERN_NON_TRACKED="core.*"
   local hit=false
-  for corefile in ${CORE_DIRECTORY}/${SEARCH_PATTERN_NON_TRACKED}; do
+  for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
     echo "Found corefile (non-tracked) at ${corefile}"
     hit=true
   done
@@ -59,7 +61,7 @@ function backtrace {
     if [[ ${hit} == true ]]; then
       echo "Processing cores..."
     fi
-    for corefile in ${CORE_DIRECTORY}/${SEARCH_PATTERN_NON_TRACKED}; do
+    for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
       filename=$(basename "${corefile}")
       binary_program=/$(echo ${filename##*.\!} | tr '!' '/')
       process_core ${binary_program} ${corefile}
@@ -73,14 +75,16 @@ function backtrace {
 }
 
 function warn_on_existing_cores() {
+  local core_directory=${1}
   local SEARCH_PATTERN_NON_TRACKED="core.*"
   # at startup warn about existing corefiles, since these are unexpected
-  for corefile in ${CORE_DIRECTORY}/${SEARCH_PATTERN_NON_TRACKED}; do
+  for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
     echo "WARNING: Found corefile (existing) at ${corefile}"
   done
 }
 
 function launch_and_wait() {
+  local core_directory=/tmp/logbt-coredumps
   if [[ $(uname -s) == 'Linux' ]]; then
     if ! which gdb > /dev/null; then
       error "Could not find required command 'gdb'"
@@ -88,8 +92,8 @@ function launch_and_wait() {
 
     # if we have sudo then set core pattern
     if [[ $(id -u) == 0 ]]; then
-      echo "Setting $(cat /proc/sys/kernel/core_pattern) -> ${CORE_DIRECTORY}/core.%p.%E"
-      echo "${CORE_DIRECTORY}/core.%p.%E" > /proc/sys/kernel/core_pattern
+      echo "Setting $(cat /proc/sys/kernel/core_pattern) -> ${core_directory}/core.%p.%E"
+      echo "${core_directory}/core.%p.%E" > /proc/sys/kernel/core_pattern
     else
       # if we cannot modify the pattern we assert it has
       # already been set as we expect and need
@@ -107,12 +111,12 @@ function launch_and_wait() {
 
     # if we have sudo then set core pattern
     if [[ $(id -u) == 0 ]]; then
-      sudo sysctl kern.corefile=${CORE_DIRECTORY}/core.%P
+      sudo sysctl kern.corefile=${core_directory}/core.%P
     else
       if [[ $(sysctl -n kern.corefile) == '/cores/core.%P' ]]; then
         # OS X default is /cores/core.%P which works for logbt out of the box
-        export CORE_DIRECTORY=/cores
-      elif [[ $(sysctl -n kern.corefile) == '${CORE_DIRECTORY}/core.%P' ]]; then
+        core_directory=/cores
+      elif [[ $(sysctl -n kern.corefile) == '${core_directory}/core.%P' ]]; then
         # all good, previously set
         :
       else
@@ -129,27 +133,27 @@ function launch_and_wait() {
     # defaults write com.apple.CrashReporter UseUNC 1
   fi
 
-  if [[ ! -d ${CORE_DIRECTORY} ]]; then
+  if [[ ! -d ${core_directory} ]]; then
     # TODO: enable this once tests are adapted to extra stdout
-    # echo "Creating directory for core files at '${CORE_DIRECTORY}'"
-    mkdir -p ${CORE_DIRECTORY}
+    # echo "Creating directory for core files at '${core_directory}'"
+    mkdir -p ${core_directory}
   fi
 
   # ensure we can write to the directory, otherwise
   # core files might not be able to be written
   WRITE_RETURN=0
-  touch ${CORE_DIRECTORY}/test.txt || WRITE_RETURN=$?
+  touch ${core_directory}/test.txt || WRITE_RETURN=$?
   if [[ ${WRITE_RETURN} != 0 ]]; then
-    error "Permissions problem: unable to write to ${CORE_DIRECTORY} (exited with ${WRITE_RETURN})"
+    error "Permissions problem: unable to write to ${core_directory} (exited with ${WRITE_RETURN})"
     exit 1
   else
     # cleanup from test
-    rm ${CORE_DIRECTORY}/test.txt
+    rm ${core_directory}/test.txt
   fi
-  warn_on_existing_cores
+  warn_on_existing_cores ${core_directory}
 
   # Hook up function to run when logbt exits
-  trap "backtrace $1" EXIT
+  trap "backtrace $1 ${core_directory}" EXIT
 
   # Enable corefile generation
   ulimit -c unlimited
