Add setup mode to logbt

diff --git a/bin/logbt b/bin/logbt
--- a/bin/logbt
+++ b/bin/logbt
@@ -4,6 +4,23 @@ set -eu
 set -o pipefail
 shopt -s nullglob
 
+PLATFORM_UNAME=$(uname -s)
+REQUIRED_FILENAME="core"
+LOGBT_VERSION="v2.0.0"
+
+if [[ ${PLATFORM_UNAME} == "Linux" ]]; then
+  REQUIRED_PATTERN="${REQUIRED_FILENAME}.%p.%E"
+  DEBUGGER="gdb"
+elif [[ ${PLATFORM_UNAME} == "Darwin" ]]; then
+  # Recommend running with the following setting to only show crashes
+  # in the notification center
+  # defaults write com.apple.CrashReporter UseUNC 1
+  REQUIRED_PATTERN="${REQUIRED_FILENAME}.%P"
+  DEBUGGER="lldb"
+else
+  error "Unsupported platform: ${PLATFORM_UNAME}"
+fi
+
 function error() {
   >&2 echo "$@"
   exit 1
@@ -12,46 +29,54 @@ function error() {
 function process_core() {
   local program=${1}
   local corefile=${2}
-  if [[ $(uname -s) == 'Darwin' ]]; then
-    lldb --core ${corefile} --batch -o 'thread backtrace all' -o 'quit'
+  local debugger=${3}
+  if [[ ${debugger} =~ "lldb" ]]; then
+    lldb --core ${corefile} --batch -o "thread backtrace all" -o "quit"
   else
     gdb ${program} --core ${corefile} -ex "set pagination 0" -ex "thread apply all bt" --batch
   fi
-  # note: on OS X the -f avoids a hang on prompt 'remove write-protected regular file?'
+  # note: on OS X the -f avoids a hang on prompt "remove write-protected regular file?"
   rm -f ${corefile}
 }
 
-function backtrace {
-  local code=$?
-  local program=${1}
-  local core_directory=${2}
-  echo "${program} exited with code:${code}"
-  if [[ $(uname -s) == 'Darwin' ]]; then
-    local single_corefile="${core_directory}/core.${CHILD_PID}"
+function find_core_by_pid() {
+  local code=${1}
+  local program=${2}
+  local core_directory=${3}
+  local debugger=${4}
+  if [[ ${PLATFORM_UNAME} == "Darwin" ]]; then
+    local single_corefile="${core_directory}/${REQUIRED_FILENAME}.${CHILD_PID}"
     if [ -e ${single_corefile} ]; then
       echo "Found corefile at ${single_corefile}"
-      process_core ${program} ${single_corefile}
+      process_core ${program} ${single_corefile} ${debugger}
     else
       if [[ ${code} != 0 ]]; then
           echo "No corefile found at ${single_corefile}"
       fi
     fi
   else
-    local SEARCH_PATTERN_BY_PID="core.${CHILD_PID}.*"
+    local SEARCH_PATTERN_BY_PID="${REQUIRED_FILENAME}.${CHILD_PID}.*"
     local hit=false
     for corefile in ${core_directory}/${SEARCH_PATTERN_BY_PID}; do
       echo "Found corefile at ${corefile}"
       # extract program name from corefile
       filename=$(basename "${corefile}")
-      binary_program=/$(echo ${filename##*.\!} | tr '!' '/')
-      process_core ${binary_program} ${corefile}
+      binary_program=/$(echo ${filename##*.\!} | tr "!" "/")
+      process_core ${binary_program} ${corefile} ${debugger}
       hit=true
     done
     if [[ ${hit} == false ]] && [[ ${code} != 0 ]]; then
         echo "No corefile found at ${core_directory}/${SEARCH_PATTERN_BY_PID}"
     fi
-  fi
-  local SEARCH_PATTERN_NON_TRACKED="core.*"
+  fi  
+}
+
+function find_remaining_cores() {
+  local code=${1}
+  local program=${2}
+  local core_directory=${3}
+  local debugger=${4}
+  local SEARCH_PATTERN_NON_TRACKED="${REQUIRED_FILENAME}.*"
   local hit=false
   for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
     echo "Found corefile (non-tracked) at ${corefile}"
@@ -62,83 +87,46 @@ function backtrace {
       echo "Processing cores..."
     fi
     for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
+      # below two lines are linux specific, but harmless to run on osx
       filename=$(basename "${corefile}")
-      binary_program=/$(echo ${filename##*.\!} | tr '!' '/')
-      process_core ${binary_program} ${corefile}
+      binary_program=/$(echo ${filename##*.\!} | tr "!" "/")
+      process_core ${binary_program} ${corefile} ${debugger}
     done
   else
     if [[ ${hit} == true ]]; then
       echo "Skipping processing cores..."
     fi
-  fi
+  fi  
+}
+
+function backtrace {
+  local code=$?
+  local program=${1}
+  local core_directory=${2}
+  local debugger=${3}
+  echo "${program} exited with code:${code}"
+  find_core_by_pid ${code} ${program} ${core_directory} ${debugger}
+  find_remaining_cores ${code} ${program} ${core_directory} ${debugger}
   exit $code
 }
 
 function warn_on_existing_cores() {
   local core_directory=${1}
-  local SEARCH_PATTERN_NON_TRACKED="core.*"
-  # at startup warn about existing corefiles, since these are unexpected
+  local SEARCH_PATTERN_NON_TRACKED="${REQUIRED_FILENAME}.*"
   for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
     echo "WARNING: Found corefile (existing) at ${corefile}"
   done
 }
 
-function launch_and_wait() {
-  local core_directory=/tmp/logbt-coredumps
-  if [[ $(uname -s) == 'Linux' ]]; then
-    if ! which gdb > /dev/null; then
-      error "Could not find required command 'gdb'"
-    fi
+function error_on_existing_cores() {
+  local core_directory=${1}
+  local SEARCH_PATTERN_NON_TRACKED="${REQUIRED_FILENAME}.*"
+  for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
+    error "Error: Found corefile (unexpected) at ${corefile}"
+  done  
+}
 
-    # if we have sudo then set core pattern
-    if [[ $(id -u) == 0 ]]; then
-      echo "Setting $(cat /proc/sys/kernel/core_pattern) -> ${core_directory}/core.%p.%E"
-      echo "${core_directory}/core.%p.%E" > /proc/sys/kernel/core_pattern
-    else
-      # if we cannot modify the pattern we assert it has
-      # already been set as we expect and need
-      if [[ $(cat /proc/sys/kernel/core_pattern) != '/tmp/logbt-coredumps/core.%p.%E' ]]; then
-        error "unexpected core_pattern: $(cat /proc/sys/kernel/core_pattern)"
-        exit 1
-      fi
-      echo "Using existing corefile location: $(cat /proc/sys/kernel/core_pattern)"
-    fi
-  else
-    if ! which lldb > /dev/null; then
-      error "Could not find required command 'lldb'"
-      exit 1
-    fi
-
-    # if we have sudo then set core pattern
-    if [[ $(id -u) == 0 ]]; then
-      sudo sysctl kern.corefile=${core_directory}/core.%P
-    else
-      if [[ $(sysctl -n kern.corefile) == '/cores/core.%P' ]]; then
-        # OS X default is /cores/core.%P which works for logbt out of the box
-        core_directory=/cores
-      elif [[ $(sysctl -n kern.corefile) == '${core_directory}/core.%P' ]]; then
-        # all good, previously set
-        :
-      else
-        # restore default with:
-        # sudo sysctl kern.corefile=/cores/core.%P
-        error "unexpected core_pattern: $(sysctl -n kern.corefile)"
-        exit 1
-      fi
-      echo "Using existing corefile location: $(sysctl -n kern.corefile)"
-    fi
-
-    # Recommend running with the following setting to only show crashes
-    # in the notification center
-    # defaults write com.apple.CrashReporter UseUNC 1
-  fi
-
-  if [[ ! -d ${core_directory} ]]; then
-    # TODO: enable this once tests are adapted to extra stdout
-    # echo "Creating directory for core files at '${core_directory}'"
-    mkdir -p ${core_directory}
-  fi
-
+function ensure_directory_is_writeable() {
   # ensure we can write to the directory, otherwise
   # core files might not be able to be written
   WRITE_RETURN=0
@@ -149,11 +137,57 @@ function launch_and_wait() {
   else
     # cleanup from test
     rm ${core_directory}/test.txt
+  fi  
+}
+
+function get_core_pattern() {
+  if [[ ${PLATFORM_UNAME} == "Linux" ]]; then
+    local core_pattern=$(cat /proc/sys/kernel/core_pattern)
+  elif [[ ${PLATFORM_UNAME} == "Darwin" ]]; then
+    # Recommend running with the following setting to only show crashes
+    # in the notification center
+    # defaults write com.apple.CrashReporter UseUNC 1
+    local core_pattern=$(sysctl -n kern.corefile)
   fi
+  echo ${core_pattern}
+}
+
+function validate_core_pattern() {
+  local core_pattern=${1}
+  if [[ ! ${core_pattern} =~ ${REQUIRED_PATTERN} ]]; then
+    error "unexpected core_pattern: ${core_pattern}"
+    exit 1
+  fi  
+}
+function launch_and_wait() {
+
+  local core_pattern=$(get_core_pattern)
+  validate_core_pattern ${core_pattern}
+
+  local core_directory=$(dirname ${core_pattern})
+  echo "Using corefile location: ${core_directory}"
+  echo "Using core_pattern: $(basename ${core_pattern})"
+
+  # ensure we have a debugger installed
+  if ! which ${DEBUGGER} > /dev/null; then
+    error "Could not find required command '${DEBUGGER}'"
+    exit 1
+  fi
+
+  # osx does not need the directory to exist, does linux?
+  if [[ ${PLATFORM_UNAME} == "Linux" ]]; then
+    if [[ ! -d ${core_directory} ]]; then
+      error "Expected directory at '${core_directory}'"
+      exit 1
+    fi
+  fi
+
+  ensure_directory_is_writeable ${core_directory}
+
   warn_on_existing_cores ${core_directory}
 
   # Hook up function to run when logbt exits
-  trap "backtrace $1 ${core_directory}" EXIT
+  trap "backtrace $1 ${core_directory} ${DEBUGGER}" EXIT
 
   # Enable corefile generation
   ulimit -c unlimited
@@ -167,4 +201,86 @@ function launch_and_wait() {
   wait ${CHILD_PID}  
 }
 
+function setup_and_exit() {
+
+  DEFAULT_CORE_DIR=/tmp/logbt
+
+  if [[ ${PLATFORM_UNAME} == "Linux" ]]; then
+    echo "Setting $(cat /proc/sys/kernel/core_pattern) -> ${DEFAULT_CORE_DIR}/${REQUIRED_PATTERN}"
+    echo "${DEFAULT_CORE_DIR}/${REQUIRED_PATTERN}" > /proc/sys/kernel/core_pattern
+  elif [[ ${PLATFORM_UNAME} == "Darwin" ]]; then
+    echo "Setting $(sysctl -n kern.corefile) -> ${DEFAULT_CORE_DIR}/${REQUIRED_PATTERN}"
+    sysctl kern.corefile=${DEFAULT_CORE_DIR}/${REQUIRED_PATTERN}
+  fi
+
+  local core_pattern=$(get_core_pattern)
+  validate_core_pattern ${core_pattern}
+  local core_directory=$(dirname ${core_pattern})
+
+  # osx does not need the directory to exist, does linux?
+  #if [[ ${PLATFORM_UNAME} == "Linux" ]]; then
+  #  if [[ ! -d ${core_directory} ]]; then
+  #    echo "Creating directory for core files at '${core_directory}'"
+  #    mkdir -p -m a+w ${core_directory}
+  #  fi
+  #fi
+
+  ensure_directory_is_writeable ${core_directory}
+  error_on_existing_cores ${core_directory}
+
+  exit 0
+
+}
+
+function usage() {
+  >&2 echo "Usage for logbt:"
+  >&2 echo ""
+  >&2 echo "Setup logbt (requires root privileges):"
+  >&2 echo ""
+  >&2 echo "$ sudo logbt --setup"
+  >&2 echo ""
+  >&2 echo "Launch another program with logbt:"
+  >&2 echo ""
+  >&2 echo "$ logbt ./program"
+  >&2 echo ""
+  >&2 echo "Error: Please either pass the --setup option or a path to a program to run"
+  exit 1
+}
+
+function get_version() {
+  echo ${LOGBT_VERSION}
+  exit 0
+}
+
+for i in "$@"
+do
+case $i in
+    --setup)
+    setup_and_exit
+    shift
+    ;;
+    --version)
+    get_version
+    shift
+    ;;
+    -v)
+    get_version
+    shift
+    ;;
+    --help)
+    usage
+    shift
+    ;;
+    -h)
+    usage
+    shift
+    ;;
+    *)
+esac
+done
+
+# if we get here, then commence launching program
+if [[ ! ${1:-} ]]; then
+  usage
+fi
 launch_and_wait $@
