rename to read-only-mode

diff --git a/bin/logbt b/bin/logbt
--- a/bin/logbt
+++ b/bin/logbt
@@ -10,8 +10,7 @@ PLATFORM_UNAME=$(uname -s)
 REQUIRED_FILENAME="core"
 LOGBT_VERSION="v2.0.3"
 BASE_CORE_DIRECTORY=/tmp/logbt-coredumps
-KEEP_CORE=false
-
+READ_ONLY_MODE=false
 
 if [[ ${PLATFORM_UNAME} == "Linux" ]]; then
   REQUIRED_PATTERN="${REQUIRED_FILENAME}.%p.%E"
@@ -44,7 +43,7 @@ function process_core() {
     gdb "${program}" --core "${corefile}" -ex "set pagination 0" -ex "${DEBUGGER_COMMAND}" --batch
   fi
   # note: on OS X the -f avoids a hang on prompt "remove write-protected regular file?"
-  if [[ ${KEEP_CORE} == false ]]; then
+  if [[ ${READ_ONLY_MODE} == false ]]; then
     rm -f "${corefile}"
   fi
 }
@@ -129,6 +128,19 @@ function error_on_existing_cores() {
   for corefile in ${core_directory}/${SEARCH_PATTERN_NON_TRACKED}; do
     error "Error: Found corefile (unexpected) at ${corefile}"
   done
+}
+
+function ensure_directory_is_writeable() {
+  # ensure we can write to the directory, otherwise
+  # core files might not be able to be written
+  WRITE_RETURN=0
+  touch "${core_directory}"/test.txt || WRITE_RETURN=$?
+  if [[ ${WRITE_RETURN} != 0 ]]; then
+    error "Error: Permissions problem: unable to write to ${core_directory} (exited with ${WRITE_RETURN})"
+  else
+    # cleanup from test
+    rm "${core_directory}"/test.txt
+  fi
 }
 
 function get_target_core_pattern() {
@@ -236,6 +248,10 @@ function launch_and_wait() {
     fi
   fi
 
+  if [[ ${READ_ONLY_MODE} == false ]]; then
+    ensure_directory_is_writeable "${core_directory}"
+  fi
+
   warn_on_existing_cores "${core_directory}"
 
   # Enable corefile generation
@@ -315,8 +331,8 @@ function setup_logbt() {
 
 }
 
-function keep_core() {
-  KEEP_CORE=true
+function set_read_only_mode() {
+  READ_ONLY_MODE=true
 }
 
 function set_debug_command() {
@@ -389,7 +405,7 @@ function usage() {
   >&2 echo ""
   >&2 echo " --current-pattern"
   >&2 echo " --target-pattern"
-  >&2 echo " --keep-core"
+  >&2 echo " --read-only-mode"
   >&2 echo " --debug-command \"thread apply all bt full\""
   exit 1
 }
@@ -417,8 +433,8 @@ case $i in
     setup_logbt
     shift
     ;;
-    --keep-core)
-    keep_core
+    --read-only-mode)
+    set_read_only_mode
     shift
     ;;
     --debug-command)
